name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  binary: smuc

jobs:
  # Build for Linux
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu
      - name: install dependencies
        run: |
          sudo apt-get update; sudo apt-get install pkg-config libasound2-dev

      - name: Build
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu

      - name: Prepare package
        run: |
          mkdir linux
          cp target/x86_64-unknown-linux-gnu/release/smuc-server linux/smuc-server
          cp target/x86_64-unknown-linux-gnu/release/smuc-client linux/smuc-client

      - name: Package as a zip
        working-directory: ./linux
        run: |
          zip --recurse-paths ../${{ env.binary }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: linux

  # Build for Windows
  release-windows:
    runs-on: windows-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: |
          cargo build --release --target x86_64-pc-windows-msvc

      - name: Prepare package
        run: |
          mkdir windows
          cp target/x86_64-pc-windows-msvc/release/smuc-server.exe windows/smuc-server.exe
          cp target/x86_64-pc-windows-msvc/release/smuc-client.exe windows/smuc-client.exe

      - name: Package as a zip
        run: |
          Compress-Archive -Path windows/* -DestinationPath ${{ env.binary }}.zip

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: windows

  # Build for macOS
  release-macos:
    runs-on: macOS-latest

    steps:
      - uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin
      - name: Environment Setup
        run: |
          export CFLAGS="-fno-stack-check"
          export MACOSX_DEPLOYMENT_TARGET="10.9"

      - name: Build
        run: |
          cargo build --release --target x86_64-apple-darwin

      - name: Prepare Package
        run: |
          mkdir -p macos/smuc-server.app/Contents/MacOS
          mkdir -p macos/smuc-client.app/Contents/MacOS
          cp target/x86_64-apple-darwin/release/smuc-server macos/smuc-server.app/Contents/MacOS/
          cp target/x86_64-apple-darwin/release/smuc-client macos/smuc-client.app/Contents/MacOS/

      - name: Package as a dmg
        working-directory: ./macos
        run: |
          hdiutil create -fs HFS+ -volname "${{ env.binary }}" -srcfolder smuc-server.app smuc-server.dmg
          hdiutil create -fs HFS+ -volname "${{ env.binary }}" -srcfolder smuc-client.app smuc-client.dmg

      - name: Package as a zip
        working-directory: ./macos
        run: |
          zip --recurse-paths ../${{ env.binary }}.zip .

      - name: Upload binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: ${{ env.binary }}.zip
          name: mac
